force-app/main/default/objects/GetAddressSettings__c/GetAddressSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Get Address Settings</label>
</CustomObject>

force-app/main/default/objects/GetAddressSettings__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <description>Sets the number of suggestions to retrieve (max 20)</description>
    <label>Count</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetAddressApiEndpoint.cls
public class GetAddressApiEndpoint extends Rest {

    private transient GetAddressSettings__c getAddressSettings = GetAddressSettings__c.getOrgDefaults();

    public GetAddressApiEndpoint() {
        calloutName = 'GetAddressApi';
    }

    public GetAddressSuggestionsResponse getSuggestions(String searchValue) {
         String endpoint = '/autocomplete/'
         + searchValue.replace(' ', '%20')
         + '?api-key=' + getAddressSettings.Apikey__c
         + '&top=' + getAddressSettings.Count__c
         + '&all=true';
        return (GetAddressSuggestionsResponse) invoke('GET', endpoint, null, GetAddressSuggestionsResponse.class);
    }
     public GetAddressResponse lookup(String url) {
        String endpoint = url + '?api-key=' + getAddressSettings.Apikey__c;
        return (GetAddressResponse) invoke('GET', endpoint, null, GetAddressResponse.class);
    }
}